---
- name: Install Nginx
  package:
    name:
      - nginx
    state: latest

- name: delete default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart nginx

- name: copy nginx site.conf
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/{{ domain }}.conf
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: Enable port http/https for Nginx with grafana reverse proxy
  firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: true
- firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: true